# -*- coding: utf-8 -*-
"""laptop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hn-v5_U2TyKNJRFQ-l5uHLBHZ6HHKVbW
"""

from datetime import datetime
import requests
import pandas as pd
from bs4 import BeautifulSoup
import re
import os
from supabase import create_client

# Supabase credentials from environment variables
SUPABASE_URL = os.environ["https://pgrriyugypdhxbitlpxj.supabase.co"]
SUPABASE_KEY = os.environ["sb_publishable_UilILiYmWcbigfuMMLlwIw_u3rQZQoa"]
supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

scrape_time = datetime.now().isoformat()
rows = []

for page in range(1, 6):
    url = f"https://www.newegg.com/p/pl?N=100017489&page={page}"
    response = requests.get(url, timeout=20)
    response.encoding = "utf-8"
    soup = BeautifulSoup(response.text, "html.parser")

    for item in soup.select(".item-container"):
        product_el = item.select_one(".item-title")
        price_el = item.select_one(".price-current strong")

        if not product_el:
            continue

        product = product_el.get_text(strip=True)
        price = price_el.get_text(strip=True).replace(",", "") if price_el else None

        rating_el = item.select_one(".item-rating i")
        rating_attr = rating_el.get("aria-label", "") if rating_el else ""
        m = re.search(r'(\d+\.?\d*)', rating_attr)
        rating = float(m.group(1)) if m else None

        ram_match = re.search(r'(\d+)\s*GB', product)
        ram_gb = int(ram_match.group(1)) if ram_match else None

        if ram_gb is None or price is None:
            continue

        rows.append({
            "product":    product,
            "price_usd":  float(price),
            "ram_gb":     ram_gb,
            "rating":     rating,
            "scraped_at": scrape_time,
        })

df = pd.DataFrame(rows)
df = df.drop_duplicates(subset="product", keep="first")

# Add price tier
df["price_tier"] = df["price_usd"].apply(
    lambda p: "Budget" if p < 600
    else ("Mid-range" if p < 1200 else "Premium")
)

# Alert: average price
avg_price = df["price_usd"].mean()
if avg_price < 600:
    print(f"⚠️ ALERT: Average price (${avg_price:.2f}) dropped below $600!")

# Push to Supabase
insert_rows = []
for _, row in df.iterrows():
    insert_rows.append({
        "product":    str(row.get("product", "")),
        "price_usd":  float(row["price_usd"]) if pd.notna(row["price_usd"]) else None,
        "ram_gb":     int(row["ram_gb"]) if pd.notna(row["ram_gb"]) else None,
        "rating":     float(row["rating"]) if pd.notna(row["rating"]) else None,
        "price_tier": str(row.get("price_tier", "")),
        "scraped_at": str(row.get("scraped_at", "")),
    })

result = supabase.table("laptops").insert(insert_rows).execute()
print(f"✅ Inserted {len(insert_rows)} rows into Supabase")